# Site
title:              The Petro Guy
bio:                'Experienced petroleum engineer and licensed real estate agent located in Dallas, Texas.'
description:        "The personal portfolio of Austin Caudill; Petroleum Engineer and Data Scientist."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thepetroguy.com" # the base hostname & protocol for your site

# Comments
disqus_shortname:   thepetroguy

# Social
analytics-id:       "UA-105785592-3"
linkedin:           austincaudill
github:             AustinCaudill
# twitter:            default
# facebook:           default
# instagram:          default


# personal
location:           Dallas, TX
phone:              XXX
email:              austinbcaudill@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg-blue.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems - Dont forget to include in Gemfile
plugins:
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-last-modified-at
  - jekyll-sitemap


paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, _EXCLUDES, RunScript]